// Listas de cartas separadas por dificuldade

export const easyCards = [
    'Black Lotus',
    'Lightning Bolt',
    'Counterspell',
    'Llanowar Elves',
    'Shivan Dragon',
    'Serra Angel',
    'Giant Growth',
    'Swords to Plowshares',
    'Wrath of God',
    'Birds of Paradise',
    'Sol Ring',
    'Dark Ritual',
    'Ancestral Recall',
    'Time Walk',
    'Tarmogoyf',
    'Snapcaster Mage',
    'Jace, the Mind Sculptor',
    'Emrakul, the Aeons Torn',
    'Blood Moon',
    'Path to Exile',
    'Thoughtseize',
    'Ragavan, Nimble Pilferer',
    'Teferi, Hero of Dominaria',
    'Primeval Titan',
    'Liliana of the Veil',
    'Goblin Guide',
    'Monastery Swiftspear',
    'Mishra’s Bauble',
    'Urza’s Saga',
    'Force of Negation',
    'Yawgmoth, Thran Physician',
    'Omnath, Locus of Creation',
    'Karn Liberated',
    'Ugin, the Spirit Dragon',
    'Nicol Bolas, the Ravager',
    'Chandra, Torch of Defiance',
    'Gideon Jura',
    'Bloodbraid Elf',
    'Expressive Iteration',
    'Wrenn and Six',
    'Fury',
    'Solitude',
    'Murktide Regent',
    'Seasoned Pyromancer',
    'Collected Company',
    'Engineered Explosives',
    'Abrupt Decay',
    'Inquisition of Kozilek',
    'Archmage’s Charm',
    'Prismatic Ending',
    'Teferi, Time Raveler',
    'Dismember',
    'Karn, the Great Creator',
    'Bloodstained Mire',
];

export const mediumCards = [
    'Lightning Bolt',
    'Ragavan, Nimble Pilferer',
    'Fury',
    'Solitude',
    'Wrenn and Six',
    'Murktide Regent',
    'Expressive Iteration',
    'Thoughtseize',
    'Scalding Tarn',
    'Misty Rainforest',
    'Verdant Catacombs',
    'Marsh Flats',
    'Arid Mesa',
    'Bloodstained Mire',
    'Wooded Foothills',
    'Windswept Heath',
    'Polluted Delta',
    'Flooded Strand',
    'Prismatic Vista',
    'Mishra’s Bauble',
    'Urza’s Saga',
    'Primeval Titan',
    'Karn, the Great Creator',
    'Blood Moon',
    'Liliana of the Veil',
    'Tarmogoyf',
    'Snapcaster Mage',
    'Path to Exile',
    'Engineered Explosives',
    'Collected Company',
    'Archmage’s Charm',
    'Seasoned Pyromancer',
    'Dismember',
    'Inquisition of Kozilek',
    'Abrupt Decay',
    'Teferi, Time Raveler',
    'Force of Negation',
    'Prismatic Ending',
    'Yawgmoth, Thran Physician',
    'Omnath, Locus of Creation',
    'Consign to Memory',
    'Nicol Bolas, the Ravager',
    'Ugin, the Spirit Dragon',
    'Teferi, Hero of Dominaria',
    'Chandra, Torch of Defiance',
    'Jace, the Mind Sculptor',
    'Emrakul, the Aeons Torn',
    'Karn Liberated',
    'Gideon Jura',
    'Goblin Charbelcher',
    'Manamorphose',
    'Desperate Ritual',
    'Pyretic Ritual',
    'Land Grant',
    'Monastery Swiftspear',
    'Eidolon of the Great Revel',
    'Lava Spike',
    'Rift Bolt',
    'Skewer the Critics',
    'Searing Blaze',
    'Searing Blood',
    'Boros Charm',
    'Lightning Helix',
    'Goblin Guide',
    'Roiling Vortex',
    'Grapeshot',
    'Past in Flames',
    'Goblin Electromancer',
    'Serum Visions',
    'Sleight of Hand',
    'Wish',
    'Amulet of Vigor',
    'Summoner’s Pact',
    'Primeval Titan',
    'Tolaria West',
    'Simic Growth Chamber',
    'Cultivator Colossus',
    'Light Up the Stage',
    'Bedlam Reveler',
    'Mutagenic Growth',
    'Gut Shot',
    'Mulldrifter',
    'Gurmag Angler',
    'Augur of Bolas',
    'Serrated Arrows',
    'Burning-Tree Emissary',
    'Skred',
    'Delver of Secrets',
    'Spellstutter Sprite',
    'Preordain',
    'Ponder',
    'Counterspell',
    'Llanowar Elves',
    'Dark Ritual',
    'Giant Growth',
    'Shivan Dragon',
    'Swords to Plowshares',
    'Wrath of God',
    'Birds of Paradise',
    'Demonic Tutor',
    'Sol Ring',
    'Black Lotus',
    'Time Walk',
    'Ancestral Recall',
    'Bloodbraid Elf'
];

export const hardCards = [
    'Sorrow’s Path',
    'Mudhole',
    'Wood Elemental',
    'One with Nothing',
    'Chimney Imp',
    'Great Wall',
    'Alabaster Leech',
    'Pale Moon',
    'Break Open',
    'Razor Boomerang',
    'Razor Pendulum',
    'Rakalite',
    'Raging River',
    'Rakalite',
    'Sorrow’s Path',
    'Bronze Tablet',
    'Tempest Efreet',
    'Divine Intervention',
    'Lich',
    'Altar of Bone',
    'Pyramids',
    'In the Eye of Chaos',
    'Invoke Prejudice',
    'Word of Command',
    'Contract from Below',
    'Timmerian Fiends',
    'Jovial Evil',
    'Raging River',
    'Bronze Tablet',
    'Tempest Efreet',
    'Divine Intervention',
    'Lich',
    'Altar of Bone',
    'Pyramids',
    'In the Eye of Chaos',
    'Invoke Prejudice',
    'Word of Command',
    'Contract from Below',
    'Timmerian Fiends',
    'Jovial Evil',
];
